### PR TITLE
serving the conten_css from public foldert

### PR DESCRIPTION
**Pull request by dagvonkr**

### CODE REVIEW

**Comment by sebastianconcept** [comment]
looks like the right thing to do! does it work @dagvonkr ? (can't check from mobile now)

**Comment by dagvonkr** [comment]
@sebastianconcept It works on chrome and safari, not firefox. But that's good enough!

**Comment by dagvonkr** [comment]
added @font-face and it works with firefox too. This looks good!

**Comment by sebastianconcept** [comment]
cool @dagvonkr 
merging

**Pull request merged**
